"""
Configuration for downtrend_breakout v1.

No-ML, futures-oriented momentum breakdown strategy with
walk-forward-first validation.
"""

from __future__ import annotations

from pathlib import Path
import json

# ── Data ─────────────────────────────────────────────────────
TIMEFRAME = "1h"
DAYS = 365
# DAYS = 1825

DEFAULT_SYMBOLS = [
    "SUI/USDT",
    "DOGE/USDT",
    "LINK/USDT",
    "BNB/USDT",
    "SOL/USDT",
    "ADA/USDT",
]

# ── Trading mode ─────────────────────────────────────────────
MODE_DEFAULT = "short_only"  # long_short | short_only
VALID_MODES = {"long_short", "short_only"}

# ── Portfolio / execution ────────────────────────────────────
INITIAL_CAPITAL = 10_000.0
POSITION_PCT = 0.15
MAX_POSITIONS = 3
FEE_PCT = 0.001          # 0.10% per side
SLIPPAGE_PCT = 0.0005    # 0.05% per side

# ── Risk / exits ─────────────────────────────────────────────
STOP_LOSS_ATR_MULT = 1.8
TAKE_PROFIT_R_MULT = 1.6
HOLD_TIMEOUT_BARS = 36
TRAIL_ACTIVATION_R = 1.0
TRAIL_ATR_MULT = 1.2

# ── Features / regime ────────────────────────────────────────
EMA_FAST = 50
EMA_SLOW = 200
EMA_SLOPE_BARS = 24
RET_6H_BARS = 6
RET_24H_BARS = 24
ATR_PERIOD = 14
ADX_PERIOD = 14
RELATIVE_VOLUME_WINDOW = 20
ATR_PERCENTILE_WINDOW = 90 * 24  # 90 days in 1h bars

# ── Signal defaults ──────────────────────────────────────────
DONCHIAN_WINDOW = 48
COOLDOWN_BARS = 8
ADX_MIN = 20.0
ATR_PERCENTILE_MAX = 90.0
RELATIVE_VOLUME_MIN = 1.0
MIN_SIGNAL_PROBABILITY = 0.60

LONG_RET24_MIN = 0.04
LONG_RET6_MIN = 0.015
SHORT_RET24_MAX = -0.05
SHORT_RET6_MAX = -0.02

# Market-context filter for safer shorts.
USE_BTC_BEAR_FILTER = True
BTC_RET24_MAX = 0.0
USE_BTC_REGIME_SWITCH = True
BTC_RET7D_MAX = -0.01
BTC_RET7D_LONG_MIN = 0.0

# Secondary short setup: sell-the-rip (mean-reversion in bearish regime).
ENABLE_SELL_THE_RIP = True
SELL_RIP_RET6H_MIN = 0.02
SELL_RIP_RET24H_MAX = 0.03

BASE_SYMBOL_PARAMS = {
    "donchian_window": DONCHIAN_WINDOW,
    "cooldown_bars": COOLDOWN_BARS,
    "adx_min": ADX_MIN,
    "atr_pct_rank_max": ATR_PERCENTILE_MAX,
    "relative_volume_min": RELATIVE_VOLUME_MIN,
    "long_ret24_min": LONG_RET24_MIN,
    "long_ret6_min": LONG_RET6_MIN,
    "short_ret24_threshold": SHORT_RET24_MAX,
    "short_ret6_threshold": SHORT_RET6_MAX,
    "min_probability": MIN_SIGNAL_PROBABILITY,
    "use_btc_bear_filter": USE_BTC_BEAR_FILTER,
    "btc_ret24_max": BTC_RET24_MAX,
    "use_btc_regime_switch": USE_BTC_REGIME_SWITCH,
    "btc_ret7d_max": BTC_RET7D_MAX,
    "btc_ret7d_long_min": BTC_RET7D_LONG_MIN,
    "enable_sell_the_rip": ENABLE_SELL_THE_RIP,
    "sell_rip_ret6h_min": SELL_RIP_RET6H_MIN,
    "sell_rip_ret24h_max": SELL_RIP_RET24H_MAX,
    "stop_loss_atr_mult": STOP_LOSS_ATR_MULT,
    "take_profit_r_mult": TAKE_PROFIT_R_MULT,
    "hold_timeout_bars": HOLD_TIMEOUT_BARS,
    "trail_activation_r": TRAIL_ACTIVATION_R,
    "trail_atr_mult": TRAIL_ATR_MULT,
}

# Static, hand-curated per-symbol overrides.
STATIC_SYMBOL_OVERRIDES: dict[str, dict] = {}

MATRIX_OVERRIDES_PATH = Path(__file__).resolve().parent / "matrix_overrides.json"
MATRIX_RUNS_DIR = Path(__file__).resolve().parent / "matrix_runs"

# ── Walk-forward ─────────────────────────────────────────────
WF_TRAIN_MONTHS = 6
WF_TEST_MONTHS = 2
WF_STEP_MONTHS = 2
WF_MIN_TRADES_FOR_PF = 5

# ── Matrix tuning grid ───────────────────────────────────────
MATRIX_RET24_GRID = [-0.03, -0.04, -0.05, -0.06]
MATRIX_DONCHIAN_GRID = [24, 36, 48, 72]
MATRIX_ADX_MIN_GRID = [16, 18, 20, 22]


def _load_matrix_overrides() -> dict[str, dict]:
    """Load optimized per-symbol params generated by matrix_test.py."""
    if not MATRIX_OVERRIDES_PATH.exists():
        return {}

    try:
        with open(MATRIX_OVERRIDES_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        return {}

    return data if isinstance(data, dict) else {}


def get_symbol_params(symbol: str) -> dict:
    """Resolve symbol params from base -> static -> matrix overrides."""
    params = dict(BASE_SYMBOL_PARAMS)
    params.update(STATIC_SYMBOL_OVERRIDES.get(symbol, {}))
    params.update(_load_matrix_overrides().get(symbol, {}))
    return params
